/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package Layer4Hysteria2 */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "main.go"







#include <stdio.h>
#include <stdlib.h>
#include <com_net_layer4_common_netty_channel_Hysteria2ProxyChannel.h>

static const char* GetJStringUTF(JNIEnv* env, jstring jstr) {
    if (jstr == NULL) return NULL;
    return (*env)->GetStringUTFChars(env, jstr, NULL);
}

static void ReleaseJStringUTF(JNIEnv* env, jstring jstr, const char* cstr) {
    if (cstr != NULL) {
        (*env)->ReleaseStringUTFChars(env, jstr, cstr);
    }
}

static jobject NewGlobalRef(JNIEnv* env, jobject obj) {
    jobject gobj = (*env)->NewGlobalRef(env, obj);
    return gobj;
}

static void DeleteGlobalRef(JNIEnv* env, jobject gobj) {
    (*env)->DeleteGlobalRef(env, gobj);
}

static JNIEnv* GetJNIEnv(JavaVM* jvm) {
    JNIEnv *env = NULL;
    if ((*jvm)->GetEnv(jvm, (void**)&env, JNI_VERSION_1_6) != JNI_OK) {
        (*jvm)->AttachCurrentThread(jvm, (void**)&env, NULL);
    }
    return env;
}

static jmethodID GetMethodID(JNIEnv* env, jobject obj, const char *name, const char *sig) {
    jclass cls = (*env)->GetObjectClass(env, obj);
    jmethodID mid = (*env)->GetMethodID(env, cls, name, sig);
    return mid;
}

static jfieldID GetfieldID(JNIEnv* env, jobject obj, const char *name, const char *sig) {
    jclass cls = (*env)->GetObjectClass(env, obj);
    jfieldID fid = (*env)->GetFieldID(env, cls, name, sig);
    return fid;
}

static jstring GetJMSGRef(JNIEnv* env, const char* msg) {
    jstring jmsg = NULL;
    if (msg != NULL) {
        jmsg = (*env)->NewStringUTF(env, msg);
    }
    return jmsg;
}

static void DelJMSGRef(JNIEnv* env, jstring jmsg) {
    if (jmsg != NULL) {
        (*env)->DeleteLocalRef(env, jmsg);
    }
}

static void SetConnectionID(JNIEnv* env, jobject obj, jlong connectionId) {
    jfieldID fid = GetfieldID(env, obj, "connectionId", "J");
    (*env)->SetLongField(env, obj, fid, connectionId);
}

static jlong GetConnectionID(JNIEnv* env, jobject obj) {
    jfieldID fid = GetfieldID(env, obj, "connectionId", "J");
    jlong connectionId = (*env)->GetLongField(env, obj, fid);
    return connectionId;
}

static void CallResp(JNIEnv* env, jobject obj, const char* name, jstring errmsg) {
    jmethodID mid = GetMethodID(env, obj, name, "(Ljava/lang/String;)V");
    (*env)->CallVoidMethod(env, obj, mid, errmsg);
}

static void CallReadResp(JNIEnv* env, jobject obj, jstring errmsg, jint len) {
    jmethodID mid = GetMethodID(env, obj, "readResp", "(Ljava/lang/String;I)V");
    (*env)->CallVoidMethod(env, obj, mid, errmsg, len);
}


#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern __declspec(dllexport) jint JNI_OnLoad(JavaVM* vm, void* reserved);
extern __declspec(dllexport) void Java_com_net_layer4_common_netty_channel_Hysteria2ProxyChannel_connectReq(JNIEnv* env, jobject obj, jstring dhost, jint dport, jstring server, jstring password, jint port, jboolean skipcertverify, jstring sni, jboolean udp);
extern __declspec(dllexport) void Java_com_net_layer4_common_netty_channel_Hysteria2ProxyChannel_readReq(JNIEnv* env, jobject obj, jlong addr, jint len);
extern __declspec(dllexport) void Java_com_net_layer4_common_netty_channel_Hysteria2ProxyChannel_writeReq(JNIEnv* env, jobject obj, jlong addr, jint len);
extern __declspec(dllexport) void Java_com_net_layer4_common_netty_channel_Hysteria2ProxyChannel_closeReq(JNIEnv* env, jobject obj);

#ifdef __cplusplus
}
#endif
