/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_net_layer4_common_hyseria2_Hysteria2Channel */

#ifndef _Included_com_net_layer4_common_hyseria2_Hysteria2Channel
#define _Included_com_net_layer4_common_hyseria2_Hysteria2Channel
#ifdef __cplusplus
extern "C" {
#endif
#undef com_net_layer4_common_hyseria2_Hysteria2Channel_BUCKET_SIZE
#define com_net_layer4_common_hyseria2_Hysteria2Channel_BUCKET_SIZE 4L
#undef com_net_layer4_common_hyseria2_Hysteria2Channel_MASK
#define com_net_layer4_common_hyseria2_Hysteria2Channel_MASK 3L
/*
 * Class:     com_net_layer4_common_hyseria2_Hysteria2Channel
 * Method:    connectReq
 * Signature: (Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;IZLjava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_com_net_layer4_common_hyseria2_Hysteria2Channel_connectReq
  (JNIEnv *, jobject, jstring, jint, jstring, jstring, jstring, jint, jboolean, jstring, jboolean);

/*
 * Class:     com_net_layer4_common_hyseria2_Hysteria2Channel
 * Method:    readReq
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_net_layer4_common_hyseria2_Hysteria2Channel_readReq
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_net_layer4_common_hyseria2_Hysteria2Channel
 * Method:    writeReq
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_net_layer4_common_hyseria2_Hysteria2Channel_writeReq
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_net_layer4_common_hyseria2_Hysteria2Channel
 * Method:    closeReq
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_net_layer4_common_hyseria2_Hysteria2Channel_closeReq
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
